apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "cyberscan.fullname" . }}-feeds
  labels: {{ include "cyberscan.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.workers.feeds.schedule | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          securityContext: {{ toYaml .Values.podSecurityContext | nindent 12 }}
          containers:
            - name: feeds
              image: {{ include "cyberscan.image" (dict "name" .Values.workers.feeds.image.name "Values" .Values) }}
              envFrom:
                - secretRef:
                    name: {{ include "cyberscan.fullname" . }}-app
              command: ["python", "-m", "cyberscan_worker.feeds.seed_fixtures"]
              resources: {{ toYaml .Values.workers.feeds.resources | nindent 16 }}
