{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "cyberscan.fullname" . }}
  labels: {{ include "cyberscan.labels" . | nindent 4 }}
  {{- if .Values.global.tls.enabled }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.global.tls.issuer | quote }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.global.domain | quote }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "cyberscan.fullname" . }}-backend
                port: { number: 8000 }
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "cyberscan.fullname" . }}-frontend
                port: { number: 3000 }
  {{- if .Values.global.tls.enabled }}
  tls:
    - hosts: [ {{ .Values.global.domain | quote }} ]
      secretName: {{ include "cyberscan.fullname" . }}-tls
  {{- end }}
{{- end }}
