apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "cyberscan.fullname" . }}-backend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: backend
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "cyberscan.fullname" . }}-frontend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: frontend
---
{{- range $pool := list "recon" "vuln" "tls" "passive" }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "cyberscan.fullname" $ }}-worker-{{ $pool }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: worker-{{ $pool }}
---
{{- end }}
