{{- range $pool, $cfg := .Values.workers }}
{{- if ne $pool "feeds" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cyberscan.fullname" $ }}-worker-{{ $pool }}
  labels: {{ include "cyberscan.labels" $ | nindent 4 }}
spec:
  replicas: {{ $cfg.replicas | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: cyberscan
      app.kubernetes.io/component: worker-{{ $pool }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cyberscan
        app.kubernetes.io/component: worker-{{ $pool }}
    spec:
      securityContext: {{ toYaml $.Values.podSecurityContext | nindent 8 }}
      containers:
        - name: worker
          image: {{ include "cyberscan.image" (dict "name" $cfg.image.name "Values" $.Values) }}
          imagePullPolicy: {{ $.Values.global.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ include "cyberscan.fullname" $ }}-app
          {{- if and (eq $pool "passive") $.Values.zap.enabled }}
          env:
            - name: ZAP_PROXY
              value: {{ printf "http://%s-zap:8090" (include "cyberscan.fullname" $) | quote }}
          {{- end }}
          command: ["celery"]
          args: ["-A", "cyberscan_worker.celery_app:celery_app", "worker", "--loglevel=info", "-Q", {{ $cfg.queues | quote }}]
          securityContext:
            capabilities:
              add: ["NET_RAW"]   # naabu SYN scans
          {{- if $.Values.nucleiTemplates.enabled }}
          volumeMounts:
            - name: nuclei-templates
              mountPath: /root/nuclei-templates
              readOnly: true
          {{- end }}
          resources: {{ toYaml $cfg.resources | nindent 12 }}
      {{- if $.Values.nucleiTemplates.enabled }}
      volumes:
        - name: nuclei-templates
          persistentVolumeClaim:
            claimName: {{ include "cyberscan.fullname" $ }}-nuclei-templates
            readOnly: true
      {{- end }}
---
{{- end }}
{{- end }}
